table '_MOD Finance Compare Selector'
	isHidden

	measure 'Metric Compare (Selected)' =
			
			SWITCH(
			  SELECTEDVALUE('_MOD Finance Compare Selector'[CompareKey], "reference_1"),
			  "reference_1", [Input Reference Measure 1],
			  "reference_2", [Input Reference Measure 2]
			)

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Metric Compare Label (Selected)' =
			
			SELECTEDVALUE('_MOD Finance Compare Selector'[Label], "BDG Mth")

	column CompareKey
		summarizeBy: none
		isNameInferred
		sourceColumn: [CompareKey]

		annotation SummarizationSetBy = Automatic

	column Label
		summarizeBy: none
		isNameInferred
		sourceColumn: [Label]

		annotation SummarizationSetBy = Automatic

	partition '_MOD Finance Compare Selector' = calculated
		mode: import
		source = ```
				
				DATATABLE(
				    "CompareKey", STRING,
				    "Label", STRING,
				    {
				        {"reference_1", "BDG Mth"},
				        {"reference_2", "Previous Year"}
				    }
				)
				```
